# Generated by Django 3.1.3 on 2020-12-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=3000)),
                ('Author', models.CharField(max_length=1000)),
                ('Supervisor', models.CharField(max_length=1000)),
                ('Degree', models.CharField(max_length=20)),
                ('Department', models.CharField(max_length=30)),
                ('Abstract', models.CharField(max_length=30000)),
                ('Date', models.DateField(max_length=10)),
            ],
        ),
    ]
