# Generated by Django 3.1.3 on 2020-12-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='Abstract',
            field=models.CharField(max_length=300000),
        ),
        migrations.AlterField(
            model_name='destination',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
