# Generated by Django 3.1.3 on 2020-12-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201204_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='Date',
            new_name='Date_column',
        ),
    ]
