# Generated by Django 3.1.3 on 2020-12-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201204_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='Date_column',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
