# Generated by Django 3.1.3 on 2020-12-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201204_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='URL',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
