# Generated by Django 3.1.4 on 2020-12-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_destination_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='Date_column',
            new_name='Date1',
        ),
    ]
